import type { Metadata } from "next";
import { Rubik, Playfair_Display } from "next/font/google"; 
import "./globals.css";

const lora = Playfair_Display({
  variable: "--font-lora",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cabinet Boujlifa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lora.variable} ${rubik.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
